// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ACCOUNT_INFO_ODB_HXX
#define ACCOUNT_INFO_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20300UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "AccountInfo.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // AccountInfo
  //
  template <>
  struct class_traits< ::AccountInfo >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::AccountInfo >
  {
    public:
    typedef ::AccountInfo object_type;
    typedef ::AccountInfo* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // AccountInfo
  //
  template <typename A>
  struct query_columns< ::AccountInfo, id_pgsql, A >
  {
    // login
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    login_type_;

    static const login_type_ login;

    // password
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned char[20],
        pgsql::id_bytea >::query_type,
      pgsql::id_bytea >
    password_type_;

    static const password_type_ password;

    // mail
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    mail_type_;

    static const mail_type_ mail;

    // premium
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    premium_type_;

    static const premium_type_ premium;

    // beta
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    beta_type_;

    static const beta_type_ beta;
  };

  template <typename A>
  const typename query_columns< ::AccountInfo, id_pgsql, A >::login_type_
  query_columns< ::AccountInfo, id_pgsql, A >::
  login (A::table_name, "\"login\"", 0);

  template <typename A>
  const typename query_columns< ::AccountInfo, id_pgsql, A >::password_type_
  query_columns< ::AccountInfo, id_pgsql, A >::
  password (A::table_name, "\"password\"", 0);

  template <typename A>
  const typename query_columns< ::AccountInfo, id_pgsql, A >::mail_type_
  query_columns< ::AccountInfo, id_pgsql, A >::
  mail (A::table_name, "\"mail\"", 0);

  template <typename A>
  const typename query_columns< ::AccountInfo, id_pgsql, A >::premium_type_
  query_columns< ::AccountInfo, id_pgsql, A >::
  premium (A::table_name, "\"premium\"", 0);

  template <typename A>
  const typename query_columns< ::AccountInfo, id_pgsql, A >::beta_type_
  query_columns< ::AccountInfo, id_pgsql, A >::
  beta (A::table_name, "\"beta\"", 0);

  template <typename A>
  struct pointer_query_columns< ::AccountInfo, id_pgsql, A >:
    query_columns< ::AccountInfo, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::AccountInfo, id_pgsql >:
    public access::object_traits< ::AccountInfo >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // login_
      //
      details::buffer login_value;
      std::size_t login_size;
      bool login_null;

      // password_
      //
      details::buffer password_value;
      std::size_t password_size;
      bool password_null;

      // mail_
      //
      details::buffer mail_value;
      std::size_t mail_size;
      bool mail_null;

      // premium_
      //
      bool premium_value;
      bool premium_null;

      // beta_
      //
      bool beta_value;
      bool beta_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::AccountInfo, id_common >:
    public access::object_traits_impl< ::AccountInfo, id_pgsql >
  {
  };

  // AccountInfo
  //
}

#include "AccountInfo-odb.ixx"

#include <odb/post.hxx>

#endif // ACCOUNT_INFO_ODB_HXX
