/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "AccountInfo" CASCADE;

CREATE TABLE "AccountInfo" (
  "login" TEXT NOT NULL PRIMARY KEY,
  "password" BYTEA NOT NULL,
  "mail" TEXT NOT NULL,
  "premium" BOOLEAN NOT NULL,
  "beta" BOOLEAN NOT NULL);

